#ifndef STATUS_H
#define STATUS_H

typedef enum {
  INITIAL, CONFIG_LOADED, NAMEDPIPE_CREATED, NAMEDPIPE_OPENED, FLIGHT_MESSAGE_QUEUE_CREATED,
  TOWER_MESSAGE_QUEUE_CREATED, SHM_LANES_CREATED, SHM_STATS_CREATED, SHM_LANES_ATTACHED,
  SHM_STATS_ATTACHED, FLIGHT_LIST_SEM_CREATED, QUEUE_SEM_CREATED, SCHEDULER_SEM_CREATED,
  TIMER_SEM_CREATED, SHM_LANES_SEM_CREATED, LOGGER_SEM_CREATED, SHM_STATS_SEM_CREATED,
  PIPE_READER_CREATED, PROCESS_CREATED
} status_t;

#endif